/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package String;

/**
 * Imports declaration
 */
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Kevin
 */
public class Reverse extends javax.swing.JFrame {
    
    /**
     * This variable holds the reversed string
     */
    private String reversed="";
    
    /**
     * Creates new form Reverse
     */
    public Reverse() {
        initComponents();
        setBackGround();
        Image icon=new ImageIcon("c:\\users\\kevin\\desktop\\image.jpeg").getImage();
        this.setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        txtOutput = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Reverse");
        setResizable(false);
        setSize(new java.awt.Dimension(400, 223));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Enter String to Reverse");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 74, 130, 20);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reversed String");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 116, 130, 20);

        txtInput.setForeground(new java.awt.Color(255, 255, 255));
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
        });
        getContentPane().add(txtInput);
        txtInput.setBounds(144, 66, 244, 30);

        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtOutput);
        txtOutput.setBounds(144, 114, 244, 30);
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 240);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This method does the hard work of reversing the input string and displaying it while user is inputing. It does simultaneous input and output.
     * @param evt The KeyEvent associated with this KeyAdapter method. Originates from initComponents where keyAdapter for txtInput is added.
     */
    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        reversed="";
        String inputs=txtInput.getText();
        for(int a=0;a<inputs.length();a++){
            char temps=inputs.charAt(a);
            reversed=String.join("",String.valueOf(temps),reversed);
        }
        txtOutput.setText(reversed);
    }//GEN-LAST:event_txtInputKeyReleased
    
   
    /**This method sets the background of the jFrame 'this' .
     * WARNING: If this code is modified and brings an error, the program reverts to default background from Nimbus look and feel.
     */
     private void setBackGround(){
        ImageIcon background=new ImageIcon("c:\\users\\kevin\\desktop\\image2.jpg");
        Image temp=background.getImage();
        Image resize=temp.getScaledInstance(lblBackground.getWidth(),lblBackground.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newResizedBackground=new ImageIcon(resize);
        lblBackground.setIcon(newResizedBackground);
        txtInput.setBackground(new Color(0,0,0,64));
        txtOutput.setBackground(new Color(0,0,0,64));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reverse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form as a thread*/
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Reverse();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
